name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - uses: aws-actions/setup-sam@v2
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - name: Go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
      - name: Lint
        run: golangci-lint run
      - name: Unit tests
        run: go test -coverprofile=coverage.out ./...
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Validate profiles
        run: |
          for f in sample-profiles/*.json; do
            jq empty "$f"
          done
      - name: Validate schema
        run: |
          pip install jsonschema
          python - <<'PY'
import json, jsonschema, glob
schema=json.load(open('schema/profile_v2.schema.json'))
for f in glob.glob('sample-profiles/*.json'):
    data=json.load(open(f))
    jsonschema.validate(data, schema)
print('schema ok')
PY
      - name: SAM validate
        run: sam validate --region us-east-1
      - name: Ensure bin directory exists
        run: mkdir -p ./bin
      - name: Build binaries
        run: make build
      - name: SAM build
        run: sam build
      - name: Dev deploy
        if: github.ref == 'refs/heads/main'
        run: sam deploy --config-env dev --no-confirm-changeset --no-fail-on-empty-changeset
      - name: Smoke invoke
        if: github.ref == 'refs/heads/main'
        run: sam local invoke GuardDuplicate --event testdata/s3_event.json
      - name: Prod deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: sam deploy --config-env prod --no-confirm-changeset --no-fail-on-empty-changeset
